export const SET_LOADING = 'SET_LOADING';
export const SET_SCREEN = 'SET_SCREEN';
export const SET_ERROR = 'SET_ERROR';

export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGOUT = 'ON_LOGOUT';

export const GET_OPEN_TRANSFER_REQUESTS = 'GET_OPEN_TRANSFER_REQUESTS';
export const SET_OPEN_TRANSFER_REQUESTS = 'SET_OPEN_TRANSFER_REQUESTS';
export const GET_MY_TRANSFER_REQUESTS = 'GET_MY_TRANSFER_REQUESTS';
export const SET_MY_TRANSFER_REQUESTS = 'SET_MY_TRANSFER_REQUESTS';
export const CLAIM_TRANSFER_REQUEST = 'CLAIM_TRANSFER_REQUEST';
export const CANCEL_TRANSFER_REQUEST = 'CANCEL_TRANSFER_REQUEST';
export const COMPLETE_TRANSFER_REQUEST = 'COMPLETE_TRANSFER_REQUEST';
export const GET_RX_DETAILS = 'GET_RX_DETAILS';
export const SET_RX_DETAILS = 'SET_RX_DETAILS';
export const GET_TRANSFER_REQUEST_HISTORY = 'GET_TRANSFER_REQUEST_HISTORY';
export const SET_TRANSFER_REQUEST_HISTORY = 'SET_TRANSFER_REQUEST_HISTORY';
