export const SET_LOADING = 'SET_LOADING';
export const SET_SCREEN = 'SET_SCREEN';

export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGOUT = 'ON_LOGOUT';

export const GET_OPEN_TRANSFER_REQUESTS = 'GET_OPEN_TRANSFER_REQUESTS';
export const SET_OPEN_TRANSFER_REQUESTS = 'SET_OPEN_TRANSFER_REQUESTS';
export const GET_MY_TRANSFER_REQUESTS = 'GET_MY_TRANSFER_REQUESTS';
export const SET_MY_TRANSFER_REQUESTS = 'SET_MY_TRANSFER_REQUESTS';
export const CLAIM_TRANSFER_REQUEST = 'CLAIM_TRANSFER_REQUEST';
export const CANCEL_TRANSFER_REQUEST = 'CANCEL_TRANSFER_REQUEST';
export const COMPLETE_TRANSFER_REQUEST = 'COMPLETE_TRANSFER_REQUEST';
